defaults:
  - _self_
  - datasets
  - model

data:

  # Available tasks: hallucination, inpainting
  task: inpainting

  # Available tasks: pdb, scope
  dataset: pdb

  loader:
    num_workers: 6
    prefetch_factor: 10

  masking_scheduler: 
    mask_schedule: False
    init_rate: 1.0
    masking_increase_ratio: 0.02

  sampler:
    # Setting for 48GB GPUs
    max_batch_size: 40
    max_num_res_squared: 150_000
    ab_max_num_res: ${pdb_dataset.ab_max_num_res}
    general_max_num_res: ${pdb_dataset.general_max_num_res}
    
interpolant:
  min_t: 1e-2
  sample_t_mode: uniform # one of ["uniform", "beta_mixed", "beta_revese_mixed", "logit_normal"]
  max_angle_deg: 0
  max_shift: 0
  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  inference_time_scaling:
    use: False

  sampling:
    num_timesteps: 35
    do_sde: False

  self_condition: ${model.edge_features.self_condition}
  save_traj: True 
  scaling_nm_ang: ${model.scaling_nm_ang}
  use_prmsd: ${model.confidence_head.use_confidence}

mini_rollout:
  min_t: 1e-2

  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  inference_time_scaling:
    use: False
  sampling:
    num_timesteps: 15
    do_sde: False

  use_prmsd: ${model.confidence_head.use_confidence}
  self_condition: ${model.edge_features.self_condition}
  save_traj: True 
  scaling_nm_ang: ${model.scaling_nm_ang}
  
experiment:
  add_modules: False
  debug: False
  seed: 123
  num_devices: 2
  warm_start: null
  warm_start_cfg_override: False
  training:
    mask_plddt: True
    bb_atom_scale: 0.1
    sc_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0 # 1.0~1.5 -> 2.0~3.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0

    aux_loss_weight: 0.3
    viol_loss_weight: 0.1
    aux_loss_use_dist_mat_loss: True
    aux_loss_use_bb_loss: True
    aux_loss_use_pair_loss: False
    aux_loss_use_chi_loss: False
    aux_loss_use_sc_atom_loss: True
    aux_loss_use_final_layer_rmsd: True
    aux_loss_use_local_dist_mat_loss: True 
    aux_loss_use_local_pair_feat_loss: ${model.distogram_head.use_pair_head}

    viol_loss_use_all_atom_clash_loss: True
    viol_loss_use_within_clash_loss: True
    viol_loss_use_bond_loss: True 

    aux_loss_use_confidence_loss: ${model.confidence_head.use_confidence}
    min_bin: 0
    max_bin: 10 

    aux_loss_dist_mat_loss_weight: 1.0
    aux_loss_bb_atom_loss_weight: 1.0 # 1.0 ~ 2.0 -> 0.2 ~ 0.3
    aux_loss_sc_atom_loss_weight: 0.5 # 0.7 ~ 1.5 -> 0.3 ~ 0.6
    aux_loss_final_layer_rmsd_weight: 1.0 
    aux_loss_local_dist_mat_loss_weight: 0.5 # 1.0 ~ 2.0 -> 0.2 ~ 0.3
    aux_loss_distogram_weight: 0.5 # 6.0 -> 2.0 ~ 3.0
    aux_loss_contact_map_weight: 0.5 # 1.0 -> 0.1 ~ 0.2

    viol_loss_all_atom_clash_loss_weight: 1.0 # 0.2 ~ 0.3 -> 0.01
    viol_loss_within_clash_loss_weight: 1.0 # 1.5 ~ 3.0 -> 0.1
    viol_loss_bond_length_weight: 0.5  # 0.2 ~ 0.5 ->
    viol_loss_ca_c_n_weight: 0.0 # 0.01 ->
    viol_loss_c_n_ca_weight: 0.0 # 0.001~0.01 -> 

    aux_loss_t_pass: 0.5
    viol_loss_t_pass: 0.75
    
  wandb:
    name: CDRFlow_v2.0.2_angle_0_shift_0
    project: v2.0.0
  optimizer:
    warmup_steps: 0
    decay_steps: 80_000
    min_lr: 1e-4
    max_lr: 1e-4
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 300
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: /home/psh/protein-frame-flow/ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: 3
    monitor: valid/h3_trans_loss
    mode: min
  # Keep this null. Will be populated at runtime.
  inference_dir: null
