defaults:
  - _self_
  - datasets
  - model

data:

  # Available tasks: hallucination, inpainting
  task: inpainting

  # Available tasks: pdb, scope
  dataset: pdb

  loader:
    num_workers: 0
    prefetch_factor: 10

  masking_scheduler: 
    mask_schedule: True
    init_rate: 0.3
    masking_increase_ratio: 0.02

  sampler:
    # Setting for 48GB GPUs
    max_batch_size: 80
    max_num_res_squared: 160_000

  # Cropping 
  ab_threshold: 40
  general_threshold: 40
  max_num_res: 450

interpolant:
  min_t: 1e-2

  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  sampling:
    num_timesteps: 20
    do_sde: False

  self_condition: ${model.edge_features.self_condition}
  save_traj: True 
  scaling_nm_ang: ${model.scaling_nm_ang}

experiment:
  add_modules: False
  debug: False
  seed: 123
  num_devices: 1
  warm_start: null
  warm_start_cfg_override: True
  training:
    mask_plddt: True
    bb_atom_scale: 0.1
    sc_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0 # 1.0~1.5 -> 2.0~3.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0

    aux_loss_use_bb_loss: True
    aux_loss_use_pair_loss: False
    aux_loss_use_chi_loss: True
    aux_loss_use_sc_atom_loss: True
    aux_loss_use_final_layer_rmsd: True
    aux_loss_use_prmsd_loss: ${model.prmsd.use_prmsd}
    aux_loss_use_all_atom_clash_loss: True
    aux_loss_use_local_dist_mat_loss: True 

    # fape loss
    aux_loss_use_fape_bb_loss: False
    aux_loss_use_fape_sc_loss: False

    aux_loss_chi_loss_weight: 1.0 # 0.7 ~ 0.9
    aux_loss_bb_atom_loss_weight: 1.0 # 1.0 ~ 2.0
    aux_loss_sc_atom_loss_weight: 0.5 # 0.7 ~ 1.5
    aux_loss_pair_loss_weight: 0.2 
    aux_loss_final_layer_rmsd_weight: 1.0 
    aux_loss_all_atom_clash_loss_weight: 100 # 5e-5 ~ 1e-4
    aux_loss_local_dist_mat_loss_weight: 2.0 # 1.0 ~ 1.5
    aux_loss_prmsd_loss_weight: 0.02 # 3.0 ~ 6.0
    
    # fape loss
    aux_loss_fape_bb_loss_weight: 4.0 # 0.3 ~ 0.4
    aux_loss_fape_sc_loss_weight: 2.0 # 0.3 ~ 0.7
    aux_loss_t_pass: 0.2
    viol_loss_t_pass: 0.5
  wandb:
    name: fm_tri_prmsd
    project: se3-fm
  optimizer:
    warmup_steps: 0
    decay_steps: 4e5
    min_lr: 1e-5
    max_lr: 1e-4
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 150
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 2
  checkpointer:
    dirpath: /home/psh/protein-frame-flow/ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: 3
    monitor: valid/h3_trans_loss
    mode: min
  # Keep this null. Will be populated at runtime.
  inference_dir: null
