defaults:
  - _self_
  - datasets
  - model

data:

  # Available tasks: hallucination, inpainting
  task: inpainting

  # Available tasks: pdb, scope
  dataset: pdb

  loader:
    num_workers: 4
    prefetch_factor: 10

  sampler:
    # Setting for 48GB GPUs
    max_batch_size: 80
    max_num_res_squared: 360_000

  # Cropping 
  ab_threshold: 40
  general_threshold: 40
  max_num_res: 600

interpolant:
  min_t: 1e-2

  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  sampling:
    num_timesteps: 100
    do_sde: False

  self_condition: ${model.edge_features.self_condition}

experiment:
  debug: False
  seed: 123
  num_devices: 1
  warm_start: null
  warm_start_cfg_override: True
  training:
    mask_plddt: True
    bb_atom_scale: 0.1
    sc_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 0.2
    aux_loss_use_bb_loss: True
    aux_loss_use_pair_loss: True
    aux_loss_use_chi_loss: True
    aux_loss_use_sc_atom_loss: True
    aux_loss_use_final_layer_rmsd: True
    aux_loss_use_prsmd_loss: True
    aux_loss_chi_loss_weight: 1.0
    aux_loss_bb_atom_loss_weight: 5.0
    aux_loss_sc_atom_loss_weight: 2.5
    aux_loss_t_pass: 0
  wandb:
    name: all_atom_framePred_sample_anchor
    project: se3-fm
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 1000
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 4
    accumulate_grad_batches: 2
  checkpointer:
    dirpath: /home/psh/protein-frame-flow/ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: 3
    monitor: valid/h3_trans_loss
    mode: min
  # Keep this null. Will be populated at runtime.
  inference_dir: null
