shared:
  seed: 123
  max_cache_size: 100_000
  samples_per_eval_length: 5
  num_eval_lengths : 8
  max_eval_length: None

  # Scaffolding parameters
  min_motif_percent: 1
  max_motif_percent: 1

  # General Loop PPI dataset or Antibody Dataset or Nanobody Dataset
  mode: affinity

pdb_dataset:
  # use unbound form 
  seed: ${shared.seed}
  train_csv_path: /home/psh/data/affinity/ppb_affinity/affinity_train_ppb.csv
  valid_csv_path: /home/psh/data/affinity/ppb_affinity/affinity_valid_ppb.csv
  train_meta_path: /home/psh/data/affinity/ppb_affinity/meta/metadata_train_ppb.csv
  valid_meta_path: /home/psh/data/affinity/ppb_affinity/meta/metadata_valid_ppb.csv

  pairs_per_cluster: 2 # 2 for ppb / 6 for abrank
  fold_threshold: 10
  upper_fold_threshold: 10000

  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 10000000
  inpainting_percent: 1.0

  add_plddt_mask: False
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Cropping 
  crop_ab: True
  ab_threshold: 40
  general_threshold: 40
  ab_max_num_res: 350
  general_max_num_res: 400

  # Filtering
  filter:
    max_num_res: 1200
    min_num_res: 100
    max_num_chain: 6
    max_mask_residues: 200
    max_coil_percent: 1.0
    rog_quantile: 1.0
    # oligomeric: ['monomeric', 'heteromer']
    # num_chains: [2,3,4,5,6,7]

  # Scaffolding
  min_motif_percent: ${shared.min_motif_percent} 
  max_motif_percent: ${shared.max_motif_percent}
  
