model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: False
  scaling_nm_ang: False 
  
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    max_num_res: 2000
    timestep_int: 1000
    embed_chain: False

  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    relpos_dim: 73
    feat_dim: 64
    num_bins: 22
    self_condition: True
    embed_chain: False
    embed_diffuse_mask: True
    embed_unit_vector: True
    embed_distogram: True
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 16
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 4

  local_triangle_attention_new:
    enable: True # true
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_rbf: 64
    c_gate_s: 16
    c_hidden: 128
    c_hidden_mul: 128
    no_heads: 4
    transition_n: 2
    k_neighbour: 32
    k_linear: 0 # residue index 상에서 앞뒤로 존재하는 얘들을 강제로 포함
    inf: 1e9
    pair_dropout: 0.25
    
  distogram_head: 
    first_break: 2
    last_break: 22
    num_bins: 64

  angle:
    c_resnet: 256
    no_resnet_blocks: 2
    no_angles: 7
    epsilon: 1.0e-07
    use_original_sm: true

  all_atom:
    n_blocks: 2
    d_single: 256
    d_hidden: 128
    atom_num: 14
    
  prmsd:
    use_prmsd: false
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 16
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 2
    num_bins: 50