model:
  c_s: 384
  c_token: 768
  c_z: 128
  num_blocks: 3
  symmetric: False
  scaling_nm_ang: False 
  
  node_features:
    c_s: 384
    c_pos_emb: 128
    c_timestep_emb: 128
    max_num_res: 2000
    timestep_int: 1000
    embed_chain: False

    aa_enc:
      c_token: 384
      has_s_z: False
      c_atom: 128
      c_atompair: 16
      c_s: ${model.c_s}
      c_z: 128
      n_blocks: 2
      n_heads: 4
      n_queries: 32
      n_keys: 128
      blocks_per_ckpt: null

  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.c_s}
    c_p: ${model.c_z}
    ref_pos_dim: 16
    relpos_k: 64
    relpos_dim: 73
    feat_dim: 64
    num_bins: 64
    min_bin: 2
    max_bin: 64
    self_condition: True
    embed_ref_pos: True
    embed_chain: False
    embed_loop_mask: True
    embed_diffuse_mask: False
    embed_unit_vector: True
    embed_distogram: True

  aa_enc:
    c_token: ${model.c_token}
    has_s_z: True
    c_atom: 128
    c_atompair: 16
    c_s: ${model.c_s}
    c_z: 128
    n_blocks: 2
    n_heads: 4
    n_queries: 32
    n_keys: 128
    blocks_per_ckpt: null

  diffusion_transformer:
    c_token: ${model.c_token}
    c_s: ${model.c_s}
    c_z: 128
    n_blocks: 12
    n_heads: 16
    drop_path_rate: 0
    blocks_per_ckpt: null
  
  aa_decoder:
    c_token: ${model.c_token}
    c_atom: 128
    c_atompair: 16
    blocks_per_ckpt: null
    n_blocks: 3
    n_heads: 4
    n_queries: 32
    n_keys: 128

  distogram_head: 
    c_z: 128
    use_pair_head: True
    min_bin: 2
    max_bin: 64
    num_bins: 64

  local_triangle_attention_new:
    enable: True # true
    c_s: ${model.c_token}
    c_z: ${model.c_z}
    c_rbf: 64
    c_gate_s: 16
    c_hidden: 128
    c_hidden_mul: 128
    no_heads: 4
    transition_n: 2
    k_neighbour: 32
    k_linear: 0 # residue index 상에서 앞뒤로 존재하는 얘들을 강제로 포함
    inf: 1e9
    pair_dropout: 0.25
    
  confidence_head:
    use_confidence: False
    c_s: ${model.c_s}
    c_z: ${model.c_z}
    num_bins: 32

  initialization:
    zero_init_condition_transition: False
    zero_init_atom_encoder_residual_linear: False
    he_normal_init_atom_encoder_small_mlp: False
    he_normal_init_atom_encoder_output: False
    glorot_init_self_attention: False
    zero_init_adaln: True
    zero_init_residual_condition_transition: False
    zero_init_dit_output: True
    zero_init_atom_decoder_linear: False