model:
  c_s: 384
  c_token: 768
  c_z: 128
  train_confidence: False
  symmetric: False
  
  node_features:
    c_s: 384
    aa_enc:
      c_token: 384
      has_s_z: False
      c_atom: 128
      c_atompair: 16
      c_s: ${model.c_s}
      c_z: 128
      n_blocks: 2
      n_heads: 4
      n_queries: 32
      n_keys: 128
      blocks_per_ckpt: null

  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.c_s}
    c_z: ${model.c_z}

    relpos: 
      r_max: 32
      s_max: 2
      c_z: ${model.c_z}
    distogram_diag:
      num_bins: 64
      min_bin: 2
      max_bin: 22
    contact_map_off_diag:
      threshold: 20
      perturb: True
      trans_scale: 4.0
      rot_scale: 0.5
      
    embed_ref_pos: True
    embed_loop_mask: True
    embed_diag_mask: True
    embed_unit_vector: True
    embed_distogram_diag: True
    embed_contact_map_off_diag: True

  pairformer: 
    n_cycles: 3
    n_blocks: 8
    n_heads: 16
    c_z: ${model.c_z}
    c_s: ${model.c_s}
    blocks_per_ckpt: 4
    dropout: 0.2

  conditioning:
    c_s: ${model.c_s}
    c_z: ${model.c_z}
    c_s_inputs: ${model.c_s}
    c_noise_embedding: 128
    relpos: 
      r_max: 32
      s_max: 2
      c_z: ${model.c_z}
  aa_enc:
    c_token: ${model.c_token}
    has_s_z: True
    c_atom: 128
    c_atompair: 16
    c_s: ${model.c_s}
    c_z: 128
    n_blocks: 3
    n_heads: 4
    n_queries: 32
    n_keys: 128
    blocks_per_ckpt: null

  diffusion_transformer:
    c_token: ${model.c_token}
    c_s: ${model.c_s}
    c_z: 128
    n_blocks: 24
    n_heads: 16
    drop_path_rate: 0
    blocks_per_ckpt: null
  
  aa_decoder:
    c_token: ${model.c_token}
    c_atom: 128
    c_atompair: 16
    blocks_per_ckpt: null
    n_blocks: 3
    n_heads: 4
    n_queries: 32
    n_keys: 128

  distogram_head: 
    c_z: 128
    use_pair_head: True
    min_bin: 2
    max_bin: 64
    num_bins: 128
    
  confidence_head:
    n_blocks: 3
    c_s: 384
    c_z: 128
    c_s_inputs: 384
    b_pae: 64
    b_plddt: 50
    max_atoms_per_token: 14
    pairformer_dropout: 0.0
    blocks_per_ckpt: null
    distance_bin_start: 3.25
    distance_bin_end: 52.0
    distance_bin_step: 1.25
    stop_gradient: True

  initialization:
    zero_init_condition_transition: False
    zero_init_atom_encoder_residual_linear: False
    he_normal_init_atom_encoder_small_mlp: False
    he_normal_init_atom_encoder_output: False
    glorot_init_self_attention: False
    zero_init_adaln: True
    zero_init_residual_condition_transition: False
    zero_init_dit_output: True
    zero_init_atom_decoder_linear: False